### ISSUE TITLE
link to "Install MKE CLI" is broken

### ISSUE THREAD

**Issue by sakshisharma84** [Mirantis/mke-docs#112]
## Issue

The link to [Install MKE CLI] in broken in getting started guide. 
https://github.com/Mirantis/mke-docs/blob/main/content/docs/getting-started/create-cluster.md

The link redirects you to https://github.com/Mirantis/mke-docs/blob/main/content/docs/install-mke-cli that gives `404 Page not found`.

![Image](https://github.com/user-attachments/assets/8a1ee7dc-1f84-49fe-b6d3-5ab9eac4aea7)

**Comment by nwneisen** [comment]
This is sending me to https://mirantis.github.io/mke-docs/docs/getting-started/install-mke-cli/

Which I believe is the desired behavior

**Comment by KoryKessel-Mirantis** [comment]
@sakshisharma84, the standard for function is not the build in GitHub. The link works on the published MKE 4 docs website:

https://mirantis.github.io/mke-docs/docs/getting-started/create-cluster/

**Comment by KoryKessel-Mirantis** [comment]
Closing issue as the function for the link on the published MKE 4 docs website works.
