### ISSUE TITLE
Adapt internal MKE 4 OIDC testing documentation for public facing doc

### ISSUE THREAD

**Issue by moshiurH** [Mirantis/mke-docs#119]
Please see the testing documentation for OIDC with screenshots and adapt them as needed to improve user experience for using OIDC with MKE 4.

https://mirantis.jira.com/wiki/spaces/TESTING/pages/5253005334/MKE+4+OIDC+Testing

**Comment by KoryKessel-Mirantis** [comment]
@moshiurH, please revisit the [OIDC MKE 4 documentation](https://mirantis.github.io/mke-docs/docs/configuration/authentication/oidc/) and the [Setting up Okta as a OIDC provider](https://mirantis.github.io/mke-docs/docs/tutorials/authentication-provider-setup/setting-up-okta-as-an-oidc-provider/) tutorial. If after doing so you still think the content needs to integrate aspects of the testing doc, please offer specific suggestions here.

**Comment by moshiurH** [comment]
I looked through the OIDC docs as well and compared to my internal notes. The official doc has enough details for setting up OIDC so I think it should be fine as is.
