### ISSUE TITLE
Adapt internal MKE 4 LDAP testing documentation for public facing doc

### ISSUE THREAD

**Issue by moshiurH** [Mirantis/mke-docs#120]
Please see the testing documentation for LDAP with screenshots and adapt them as needed to improve user experience for using LDAP with MKE 4.

https://mirantis.jira.com/wiki/spaces/TESTING/pages/5283446802/MKE+4+LDAP+Testing

**Comment by KoryKessel-Mirantis** [comment]
@moshiurH, please revisit the [LDAP MKE 4 documentation](https://mirantis.github.io/mke-docs/docs/configuration/authentication/ldap/) and the [Setting up OpenLDAP as a LDAP provider](https://mirantis.github.io/mke-docs/docs/tutorials/authentication-provider-setup/setting-up-openldap-as-an-ldap-provider/) tutorial. If after doing so you still think the content needs to integrate aspects of the testing doc, please offer specific suggestions here.

**Comment by KoryKessel-Mirantis** [comment]
Covered by https://github.com/Mirantis/mke-docs/pull/167.
