### ISSUE TITLE
Adapt internal MKE 4 SAML testing documentation for public facing doc

### ISSUE THREAD

**Issue by moshiurH** [Mirantis/mke-docs#121]
Please see the testing documentation for SAML with screenshots and adapt them as needed to improve user experience for using SAML with MKE 4.

https://mirantis.jira.com/wiki/spaces/TESTING/pages/5217910809/MKE+4+SAML+Testing

**Comment by KoryKessel-Mirantis** [comment]
@moshiurH, please revisit the [SAML MKE 4 documentation](https://mirantis.github.io/mke-docs/docs/configuration/authentication/saml/) and the [Setting up Okta as a SAML provider](https://mirantis.github.io/mke-docs/docs/tutorials/authentication-provider-setup/setting-up-okta-as-a-saml-provider/). If after doing so you still think the content needs to integrate aspects of the testing doc, please offer specific suggestions here.

**Comment by moshiurH** [comment]
I reviewed the SAML documentation and it looks great. I think the doc is sufficiently detailed. If enough customers complain, we can add more granular details!
