### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by brianbancroft** [Mirantis/mke-docs#131]
In MKE-Dashboard, the licensing page will point to a licensing docs page for more information and one does not exist yet. 

## What is needed

- How to procure a new license (including contact points) for those who are unaware
- Anything relevant from https://docs.mirantis.com/mke/3.7/install/obtain-license.html?highlight=license

**Comment by byDimasik** [comment]
License can be set either via config file or UI.

### Config

The config way is straightforward

1. Set the license token under `spec.license.token`
  ```yaml
  spec:
    license:
      token: <your-license-token>
  ```
2. Run `mkectl apply`

To check the license status, users can see the status of the `mkeconfig` resource
```shell
kubectl -n mke get mkeconfig mke -ojsonpath="{.status.licenseStatus}" | jq 
```

Example output
```
{
  "expiration": "2027-10-10T07:00:00Z",
  "licenseType": "Offline",
  "maxEngines": 10,
  "scanningEnabled": true,
  "subject": "sf|0014W0000341gYFQAY|a2X4W000000ZeatUAC",
  "tier": "Production"
}
```

### UI

UI should be almost identical to what we have in [MKE 3 docs](https://docs.mirantis.com/mke/3.7/install/obtain-license.html)

Just the upload button is named differently and in addition to uploading a file we allowed pasting the token as a string into a text box. @brianbancroft do you have a screenshot of the most recent version of the license page

**Comment by brianbancroft** [comment]
@byDimasik the purpose of this help page is to help the user understand who to contact and how to procure a license.

**Comment by rachaelbrownie** [comment]
That said, the "learn more" in that screenshot would be good to go to a page with the content that you have written here @byDimasik, but then to address the concern Brian has raised for this specific issue, we should also need  (as Brian said) some place to direct users to that describes how to purchase/renew a license; whether thats a page, a phone number, email etc). And it would be great in the page outlined above to provide a link to that information as well. 

In the end.
1. A user should click on "learn more" and it goes to a page describing how to update and has a link to a page on how to purchase/renew or a contact page.
2. A user should click on the "purchase a license" in the license banner and it goes directly to that page on how to purchase/renew/contact page.

**Comment by rachaelbrownie** [comment]
Further, once they are on the page for Adding a License, documentation on how to get there or how to update it by CLI probably isn't that helpful 😅 . So it's good to have, but yeah, not specifically what we are looking for here.

**Comment by brianbancroft** [comment]
![Image](https://github.com/user-attachments/assets/0c3cfec2-3f8a-4972-b527-d27d37ef3453)

here is a screenshot on the page used to add a license as well.

**Comment by brianbancroft** [comment]
Still noticing that the `obtain-license.md` has plenty on how to use a license. Will there be instructions on how to obtain a license? https://github.com/Mirantis/mke-docs/blob/32044c349da238aadd7910716bd4cf7beecbf0b2/content/docs/getting-started/obtain-license.md

**Comment by ry4nz** [comment]
@MagdaDziadosz If we’re currently missing details on obtaining a license in MKE 4, what would you recommend the page should include to ensure it’s clear and useful for users? Your insights as both a writer and potential user would be highly valuable.

**Comment by MagdaDziadosz** [comment]
@ry4nz @brianbancroft Currently, the licensing page includes more information than the one in MKE 3, we have a link to a contact form and explanation on how to apply the license through the UI as well as configuration file. Technical documentation is a place where users seek information after they start using the product. However, if you think adding a link to a pricing page or email address of our sales department would be beneficial, I can certainly do so (you just need to provide it). That being said, obtaining a license seems like a main page topic. The main page is where the customers will first look for information on a product and pricing.

**Comment by rachaelbrownie** [comment]
I actually didn't see the PR that was attached to this until just now. 

How about just below `information, refer to [Mirantis Agreements and Terms](https://legal.mirantis.com/).` we add a line:

"If you are need a license or your license has expired please contact [x] or go to [Y]"

Maybe that's all we need. I agree that users coming to this page probably already have purchased but I think a few extra links to where to give us money cant hurt. 

Otherwise the PR looks great IMO and should definitely solve what we need. Unless @ry4nz  or @brianbancroft  think there is still something missing besides that.

**Comment by rachaelbrownie** [comment]
And once its good i will update the link on the Licensing page in the UI to link to this. To confirm @MagdaDziadosz , the URL will be: `https://mirantis.github.io/mke-docs/docs/getting-started/obtain-license`?

**Comment by rachaelbrownie** [comment]
@MagdaDziadosz so to be clear, you need us to provide the x and y to you?

**Comment by MagdaDziadosz** [comment]
@rachaelbrownie yes, I don't know who the customers need to contact to obtain the license, so if such information is to be included in the documentation, you need to provide all the details.

**Comment by KoryKessel-Mirantis** [comment]
Agreed to table x/y discussion. Issue handled with https://github.com/Mirantis/mke-docs/pull/179.
