### ISSUE TITLE
Missing: The ability to disable telemetry will be disabled for unlicensed copies of MKE-4.

### ISSUE THREAD

**Issue by brianbancroft** [Mirantis/mke-docs#132]
While working on the licensing section, I encountered this page. https://mirantis.github.io/mke-docs/docs/operations/telemetry/

It has come to my attention that the ability to disable telemetry for unlicensed copies of MKE-4 will not be permitted and such behavior will be added to the relevant page in mke-dashboard. It might be also worth adding this information to the telemetry page in the form of a small callout.

**Comment by KoryKessel-Mirantis** [comment]
@brianbancroft, I dropped a note into https://github.com/Mirantis/mke-docs/pull/128, requesting that @RaunakShah drop a rough note in that I will sharpen up for publication.

**Comment by KoryKessel-Mirantis** [comment]
Merged https://github.com/Mirantis/mke-docs/pull/128, which addressed the issue.
