### ISSUE TITLE
Alias for a kubectl command being used in Known Issues for password retrieval

### ISSUE THREAD

**Issue by rleap-m** [Mirantis/mke-docs#172]
## Description

It appears a typo or an alias (`% km`) was used for a `kubectl` command which shows admin password information.  Without an alias for `km` in a Bash terminal the user will get this error: `-bash: fg: %: no such job`

## URL of Page

https://mirantis.github.io/mke-docs/docs/release-notes/known-issues/#bop-982-cannot-change-mke-4-password-using-mkectl

## What we currently have

2. Reveal the Password object for the target user.

```bash
$ % km get password mfsg22lozpzjzzeeeirsk -oyaml
```

## Suggested edit

2. Reveal the Password object for the target user.

```bash
$ kubectl -n mke get password mfsg22lozpzjzzeeeirsk -oyaml
```

**Comment by nwneisen** [comment]
Also worth noting that being able to change the user's password is not the expected behavior for `mkectl apply --admin-password`. This field is for setting the default admin password when the cluster is first created, not changing it once it already exists.
