### ISSUE TITLE
Update GPU not supported features

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/mke-docs#190]
Update the GPU section in https://mirantis.github.io/mke-docs/docs/release-notes/features/ or other appropriate page to mention that Nvidia MIG is not supported.

This was supported in MKE3 but it was only mentioned as a config value and not on the GPU config page so it was missed. GPU node discovery was also the priority for GPU support.

**Comment by KoryKessel-Mirantis** [comment]
@nwneisen, please take a look at the edits made to the **New features** page in https://github.com/Mirantis/mke-docs/pull/197 and fine-tune this direction.

**Comment by KoryKessel-Mirantis** [comment]
Handled with https://github.com/Mirantis/mke-docs/pull/197.
