### ISSUE TITLE
Document basic authentication

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/mke-docs#194]
A section should be added under authorization for basic authentication. This should cover

- The default admin user that is created when creating a fresh cluster. Specifically point out that the password for this user is printed to the terminal after installation and this is the only place to get this password. This should also be pointed out in the getting started process.
- Managing basic authentication users through the UI

Note: There is an HTTP api endpoint for user management but I did not mention it here for these reasons
- It is still in flux and the endpoints and their criteria could change
- It's not actually needed. `mkectl` is now creating users by creating k8s password objects directly. The UI could do the same
- I'm not sure if we planned on telling users about the HTTP endpoints

**Suggested page layout**

## Default admin user

An admin user is created by default when creating a fresh cluster. This admin will always have the username `admin` and a randomly generated password. This password is printed out after successfully creating the cluster. 

> Note: This password is not stored anywhere on the cluster and cannot be retrieved in any way. If the password is not saved in the install output logs, the cluster will need to be recreated to gain access.

## Managing users

All user management is done through the MKE dashboard in the Users section. The user management page is located under `Access Control` -> `Users`. You will need to be logged in with an admin account in order to have access to and make changes to users.

## Creating a user
To create a user, click the blue `+ Create User` button on the right side of the page. This will take you to the user creation page

The following fields are required for a new user

```
username
password
confirm password
```

If you are creating another admin user, check the `admin` box to make the user an admin.

```
name
```
The name of the user is also available but this is an optional field and not used by anything in the MKE system.

## Changing a password
To change a users, click on the user's name in the list to change to the user's page. In the top right of the user's page, click the `Update Password` button. You will be asked to enter the new password and confirm the new password.

## Deleting a user
To delete a user, you must first check the box on the left of the user on the user management page. Once it is checked, the `actions` dropdown in the top right of the page will now have the option to `remove` the user. This method allows multiple users to be removed at once.

You may also click on the user's name to change to the user's page with all of their specific information. Click on `Delete` in the top right of their page to remove the user from the system.

**Comment by ry4nz** [comment]
Shall we also add sections for changing passwords?

**Comment by nwneisen** [comment]
I updated this to be managing users through the UI

**Comment by KoryKessel-Mirantis** [comment]
Handled with https://github.com/Mirantis/mke-docs/pull/217.
