### ISSUE TITLE
Documentation on key differences between MKE3 and MKE4 UI

### ISSUE THREAD

**Issue by rachaelbrownie** [Mirantis/mke-docs#204]
The key changes have been identified here. We should fine a way to shared this information with users.

https://mirantis.jira.com/wiki/spaces/BOP/pages/5716312115/Web+UI+Dashboard#Key-changes

**Comment by KoryKessel-Mirantis** [comment]
Created https://mirantis.jira.com/browse/ENGDOCS-2517 around the ask and will close this Issue.

**Comment by rachaelbrownie** [comment]
thanks Kory!
