### ISSUE TITLE
Documentation on Certificates

### ISSUE THREAD

**Issue by rachaelbrownie** [Mirantis/mke-docs#205]
We have links to relevant documentation for every other page in the admin settings here https://mirantis.github.io/mke-docs/docs/configuration/. Is it possible we can add some docs / a docs page for certificates as well?

![Image](https://github.com/user-attachments/assets/3671dd23-67cb-4b92-9180-29f04474593d)

**Comment by KoryKessel-Mirantis** [comment]
@rachaelbrownie, we can certainly add a page on Certificates, though it will not happen before tomorrow's GA. I have opened https://mirantis.jira.com/browse/ENGDOCS-2516 in reference to the ask, citing you as the Reporter, and will close this GitHub issue.

**Comment by rachaelbrownie** [comment]
perfectly reasonable. Thank you!
