### ISSUE TITLE
Manual install for MKE4 points to mkectl rc5 release

### ISSUE THREAD

**Issue by aldr1c** [Mirantis/mke-docs#248]
Under manual install below links are pointing to rc5 when they should point into GA release 

https://mirantis.github.io/mke-docs/docs/getting-started/install-mke-cli/#install-manually

https://s3.us-east-2.amazonaws.com/packages-stage-mirantis.com/v4.0.0-rc.5/mkectl_linux_x86_64.tar.gz

**Comment by nwneisen** [comment]
These should be updated to point to the latest release. They then wont need to be updated in the future. @sakshisharma84

**Comment by KoryKessel-Mirantis** [comment]
Covered by [#250](https://github.com/Mirantis/mke-docs/pull/250).
