### ISSUE TITLE
Start interacting with the cluster reffring to ~/.mke/mke.kubeconfig  and it should to~/.mke/mke.kubeconf

### ISSUE THREAD

**Issue by aldr1c** [Mirantis/mke-docs#253]
This is a cosmetic issue, but it could potentially confuse the end user and give the false impression that the kubeconfig was not generated.

On the doc webpage below, it refers to ~/.mke/mke.kubeconfig when it should be ~/.mke/mke.kubeconf

`ls -l .mke/
total 8
-rw------- 1 root root 5709 Dec  6 13:32 mke.kubeconf`

https://mirantis.github.io/mke-docs/docs/getting-started/start-interacting-with-cluster/

**Comment by nwneisen** [comment]
Fixed with #255
