### ISSUE TITLE
Instruction to enable telemetry does not match accompanying YAML

### ISSUE THREAD

**Issue by quadespresso** [Mirantis/mke-docs#273]
In this block:

https://github.com/Mirantis/mke-docs/blob/main/content/docs/configuration/telemetry.md?plain=1#L28-L34

the instruction references `telemetry.enabled`, whereas the YAML references `tracking.enabled` (`spec.tracking.enabled` to be precise).

I saw that this was added in #125 -- tagging @byDimasik

**Comment by byDimasik** [comment]
good catch 👍
