### ISSUE TITLE
Add an LDAP server example

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/mke-docs#91]
We currently have a dev setup that makes it easy to run an LDAP server for testing against: https://github.com/MirantisContainers/mke/blob/main/docs/dev/dex-LDAP-server.md

This should be added to our public docs so that customers can just as easily run an LDAP server for testing against

This will include the
- docker-compose.yml code for the LDAP server
- The ldif file that gets copied into the container
- The MKE4 config
- The docker compose command

**Comment by KoryKessel-Mirantis** [comment]
Done dooby doo done done.
