### ISSUE TITLE
Incorrect edit link

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/mke-docs#93]
The edit page link is currently set to `https://github.com/Mirantis/mke-docs/edit/main/README.md`

When you click this on any sub page, it creates and opens the wrong path in the browser.

It should actually be `https://github.com/Mirantis/mke-docs/edit/main/content/` so that any page opens the correct file in github to edit.

**Comment by quadespresso** [comment]
Think I got it sorted with this PR: https://github.com/Mirantis/mke-docs/pull/98
